/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, BamlCtxManager, ClientRegistry, Image, Audio, Pdf, Video } from "@boundaryml/baml"
import { toBamlError, HTTPRequest } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type * as types from "./types"
import type {AnalysisDepth, BoardMember, DeepIntelligenceOutput, FinancialViabilityAnalysis, GeographicAnalysis, HistoricalAnalysis, HistoricalGrant, NetworkAnalysis, NetworkConnection, OperationalReadinessAnalysis, PolicyAlignment, PolicyAnalysis, RelationshipMap, RiskAssessment, RiskFactor, RiskLevel, StrategicConsultingInsights, StrategicFitAnalysis, SuccessProbability} from "./types"
import type TypeBuilder from "./type_builder"

type BamlCallOptions = {
  tb?: TypeBuilder
  clientRegistry?: ClientRegistry
  env?: Record<string, string | undefined>
}

export class HttpRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  AnalyzeCompleteDepth(
      opportunity_title: string,opportunity_description: string,funder_name: string,organization_name: string,organization_mission: string,screening_score?: number | null,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "AnalyzeCompleteDepth",
        {
          "opportunity_title": opportunity_title,"opportunity_description": opportunity_description,"funder_name": funder_name,"organization_name": organization_name,"organization_mission": organization_mission,"screening_score": screening_score?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AnalyzeEnhancedDepth(
      opportunity_title: string,opportunity_description: string,funder_name: string,organization_name: string,organization_mission: string,screening_score?: number | null,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "AnalyzeEnhancedDepth",
        {
          "opportunity_title": opportunity_title,"opportunity_description": opportunity_description,"funder_name": funder_name,"organization_name": organization_name,"organization_mission": organization_mission,"screening_score": screening_score?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AnalyzeEssentialsDepth(
      opportunity_title: string,opportunity_description: string,funder_name: string,funder_type: string,organization_name: string,organization_mission: string,organization_ein: string,screening_score?: number | null,opportunity_amount_min?: number | null,opportunity_amount_max?: number | null,opportunity_deadline?: string | null,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "AnalyzeEssentialsDepth",
        {
          "opportunity_title": opportunity_title,"opportunity_description": opportunity_description,"funder_name": funder_name,"funder_type": funder_type,"organization_name": organization_name,"organization_mission": organization_mission,"organization_ein": organization_ein,"screening_score": screening_score?? null,"opportunity_amount_min": opportunity_amount_min?? null,"opportunity_amount_max": opportunity_amount_max?? null,"opportunity_deadline": opportunity_deadline?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AnalyzePremiumDepth(
      opportunity_title: string,opportunity_description: string,funder_name: string,funder_type: string,organization_name: string,organization_mission: string,organization_ein: string,screening_score?: number | null,opportunity_amount_min?: number | null,opportunity_amount_max?: number | null,opportunity_deadline?: string | null,target_funder_board?: string[] | null,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "AnalyzePremiumDepth",
        {
          "opportunity_title": opportunity_title,"opportunity_description": opportunity_description,"funder_name": funder_name,"funder_type": funder_type,"organization_name": organization_name,"organization_mission": organization_mission,"organization_ein": organization_ein,"screening_score": screening_score?? null,"opportunity_amount_min": opportunity_amount_min?? null,"opportunity_amount_max": opportunity_amount_max?? null,"opportunity_deadline": opportunity_deadline?? null,"target_funder_board": target_funder_board?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AnalyzeQuickDepth(
      opportunity_title: string,opportunity_description: string,funder_name: string,organization_name: string,organization_mission: string,screening_score?: number | null,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "AnalyzeQuickDepth",
        {
          "opportunity_title": opportunity_title,"opportunity_description": opportunity_description,"funder_name": funder_name,"organization_name": organization_name,"organization_mission": organization_mission,"screening_score": screening_score?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AnalyzeStandardDepth(
      opportunity_title: string,opportunity_description: string,funder_name: string,organization_name: string,organization_mission: string,screening_score?: number | null,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "AnalyzeStandardDepth",
        {
          "opportunity_title": opportunity_title,"opportunity_description": opportunity_description,"funder_name": funder_name,"organization_name": organization_name,"organization_mission": organization_mission,"screening_score": screening_score?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export class HttpStreamRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  AnalyzeCompleteDepth(
      opportunity_title: string,opportunity_description: string,funder_name: string,organization_name: string,organization_mission: string,screening_score?: number | null,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "AnalyzeCompleteDepth",
        {
          "opportunity_title": opportunity_title,"opportunity_description": opportunity_description,"funder_name": funder_name,"organization_name": organization_name,"organization_mission": organization_mission,"screening_score": screening_score?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AnalyzeEnhancedDepth(
      opportunity_title: string,opportunity_description: string,funder_name: string,organization_name: string,organization_mission: string,screening_score?: number | null,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "AnalyzeEnhancedDepth",
        {
          "opportunity_title": opportunity_title,"opportunity_description": opportunity_description,"funder_name": funder_name,"organization_name": organization_name,"organization_mission": organization_mission,"screening_score": screening_score?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AnalyzeEssentialsDepth(
      opportunity_title: string,opportunity_description: string,funder_name: string,funder_type: string,organization_name: string,organization_mission: string,organization_ein: string,screening_score?: number | null,opportunity_amount_min?: number | null,opportunity_amount_max?: number | null,opportunity_deadline?: string | null,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "AnalyzeEssentialsDepth",
        {
          "opportunity_title": opportunity_title,"opportunity_description": opportunity_description,"funder_name": funder_name,"funder_type": funder_type,"organization_name": organization_name,"organization_mission": organization_mission,"organization_ein": organization_ein,"screening_score": screening_score?? null,"opportunity_amount_min": opportunity_amount_min?? null,"opportunity_amount_max": opportunity_amount_max?? null,"opportunity_deadline": opportunity_deadline?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AnalyzePremiumDepth(
      opportunity_title: string,opportunity_description: string,funder_name: string,funder_type: string,organization_name: string,organization_mission: string,organization_ein: string,screening_score?: number | null,opportunity_amount_min?: number | null,opportunity_amount_max?: number | null,opportunity_deadline?: string | null,target_funder_board?: string[] | null,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "AnalyzePremiumDepth",
        {
          "opportunity_title": opportunity_title,"opportunity_description": opportunity_description,"funder_name": funder_name,"funder_type": funder_type,"organization_name": organization_name,"organization_mission": organization_mission,"organization_ein": organization_ein,"screening_score": screening_score?? null,"opportunity_amount_min": opportunity_amount_min?? null,"opportunity_amount_max": opportunity_amount_max?? null,"opportunity_deadline": opportunity_deadline?? null,"target_funder_board": target_funder_board?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AnalyzeQuickDepth(
      opportunity_title: string,opportunity_description: string,funder_name: string,organization_name: string,organization_mission: string,screening_score?: number | null,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "AnalyzeQuickDepth",
        {
          "opportunity_title": opportunity_title,"opportunity_description": opportunity_description,"funder_name": funder_name,"organization_name": organization_name,"organization_mission": organization_mission,"screening_score": screening_score?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AnalyzeStandardDepth(
      opportunity_title: string,opportunity_description: string,funder_name: string,organization_name: string,organization_mission: string,screening_score?: number | null,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const env: Record<string, string> = Object.fromEntries(
        Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
      );
      return this.runtime.buildRequestSync(
        "AnalyzeStandardDepth",
        {
          "opportunity_title": opportunity_title,"opportunity_description": opportunity_description,"funder_name": funder_name,"organization_name": organization_name,"organization_mission": organization_mission,"screening_score": screening_score?? null
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}