/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum AnalysisDepth {
  ESSENTIALS = "ESSENTIALS",
  PREMIUM = "PREMIUM",
  QUICK = "QUICK",
  STANDARD = "STANDARD",
  ENHANCED = "ENHANCED",
  COMPLETE = "COMPLETE",
}

export enum RiskLevel {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum SuccessProbability {
  VERY_LOW = "VERY_LOW",
  LOW = "LOW",
  MODERATE = "MODERATE",
  HIGH = "HIGH",
  VERY_HIGH = "VERY_HIGH",
}

export interface BoardMember {
  name: string
  title?: string | null
  affiliations: string[]
  influence_score?: number | null
  
}

export interface DeepIntelligenceOutput {
  strategic_fit: StrategicFitAnalysis
  financial_viability: FinancialViabilityAnalysis
  operational_readiness: OperationalReadinessAnalysis
  risk_assessment: RiskAssessment
  proceed_recommendation: boolean
  success_probability: SuccessProbability
  overall_score: number
  executive_summary: string
  key_strengths: string[]
  key_challenges: string[]
  recommended_next_steps: string[]
  historical_intelligence?: HistoricalAnalysis | null
  geographic_analysis?: GeographicAnalysis | null
  network_intelligence?: NetworkAnalysis | null
  relationship_mapping?: RelationshipMap | null
  policy_analysis?: PolicyAnalysis | null
  strategic_consulting?: StrategicConsultingInsights | null
  depth_executed: string
  processing_time_seconds: number
  api_cost_usd: number
  timestamp: string
  tool_version: string
  
}

export interface FinancialViabilityAnalysis {
  viability_score: number
  budget_capacity_score: number
  financial_health_score: number
  sustainability_score: number
  budget_implications: string
  resource_requirements: Record<string, string>
  financial_risks: string[]
  financial_strategy: string
  budget_recommendations: string[]
  
}

export interface GeographicAnalysis {
  primary_service_area: string
  funder_geographic_focus: string
  geographic_alignment_score: number
  geographic_fit_assessment: string
  regional_competition_analysis: string
  location_advantages: string[]
  location_challenges: string[]
  
}

export interface HistoricalAnalysis {
  historical_grants: HistoricalGrant[]
  total_grants_analyzed: number
  total_funding_amount: number
  average_grant_size: number
  typical_grant_range: string
  funding_trends: string
  geographic_patterns: string
  similar_recipient_profiles: string[]
  success_factors: string[]
  competitive_intelligence: string
  
}

export interface HistoricalGrant {
  recipient_name: string
  grant_amount: number
  grant_year: number
  purpose: string
  geographic_location?: string | null
  
}

export interface NetworkAnalysis {
  board_connections: BoardMember[]
  network_connections: NetworkConnection[]
  network_strength_score: number
  relationship_advantages: string[]
  relationship_leverage_strategy: string
  key_contacts_to_cultivate: string[]
  
}

export interface NetworkConnection {
  connection_type: string
  connected_entity: string
  strength: number
  description: string
  
}

export interface OperationalReadinessAnalysis {
  readiness_score: number
  capacity_score: number
  timeline_feasibility_score: number
  infrastructure_readiness_score: number
  capacity_gaps: string[]
  infrastructure_requirements: string[]
  timeline_challenges: string[]
  capacity_building_plan: string
  operational_recommendations: string[]
  estimated_preparation_time_weeks: number
  
}

export interface PolicyAlignment {
  relevant_policies: string[]
  alignment_score: number
  policy_opportunities: string[]
  policy_risks: string[]
  
}

export interface PolicyAnalysis {
  federal_policy_alignment: PolicyAlignment
  state_policy_alignment?: PolicyAlignment | null
  policy_landscape_summary: string
  policy_opportunities: string[]
  advocacy_recommendations: string[]
  
}

export interface RelationshipMap {
  direct_relationships: string[]
  indirect_relationships: string[]
  partnership_opportunities: string[]
  relationship_insights: string
  cultivation_strategy: string
  
}

export interface RiskAssessment {
  overall_risk_level: RiskLevel
  overall_risk_score: number
  risk_factors: RiskFactor[]
  critical_risks: string[]
  manageable_risks: string[]
  risk_mitigation_plan: string
  
}

export interface RiskFactor {
  category: string
  risk_level: RiskLevel
  description: string
  impact: string
  mitigation_strategy: string
  probability: number
  
}

export interface StrategicConsultingInsights {
  executive_summary: string
  competitive_positioning: string
  differentiation_strategy: string
  multi_year_funding_strategy: string
  partnership_development_strategy: string
  capacity_building_roadmap: string
  immediate_actions: string[]
  medium_term_actions: string[]
  long_term_actions: string[]
  
}

export interface StrategicFitAnalysis {
  fit_score: number
  mission_alignment_score: number
  program_alignment_score: number
  geographic_alignment_score: number
  alignment_strengths: string[]
  alignment_concerns: string[]
  strategic_rationale: string
  strategic_positioning: string
  key_differentiators: string[]
  
}
