/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  AnalysisDepth,  BoardMember,  DeepIntelligenceOutput,  FinancialViabilityAnalysis,  GeographicAnalysis,  HistoricalAnalysis,  HistoricalGrant,  NetworkAnalysis,  NetworkConnection,  OperationalReadinessAnalysis,  PolicyAlignment,  PolicyAnalysis,  RelationshipMap,  RiskAssessment,  RiskFactor,  RiskLevel,  StrategicConsultingInsights,  StrategicFitAnalysis,  SuccessProbability } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface BoardMember {
      name?: string | null
      title?: string | null
      affiliations: string[]
      influence_score?: number | null
    }
    export interface DeepIntelligenceOutput {
      strategic_fit?: StrategicFitAnalysis | null
      financial_viability?: FinancialViabilityAnalysis | null
      operational_readiness?: OperationalReadinessAnalysis | null
      risk_assessment?: RiskAssessment | null
      proceed_recommendation?: boolean | null
      success_probability?: types.SuccessProbability | null
      overall_score?: number | null
      executive_summary?: string | null
      key_strengths: string[]
      key_challenges: string[]
      recommended_next_steps: string[]
      historical_intelligence?: HistoricalAnalysis | null
      geographic_analysis?: GeographicAnalysis | null
      network_intelligence?: NetworkAnalysis | null
      relationship_mapping?: RelationshipMap | null
      policy_analysis?: PolicyAnalysis | null
      strategic_consulting?: StrategicConsultingInsights | null
      depth_executed?: string | null
      processing_time_seconds?: number | null
      api_cost_usd?: number | null
      timestamp?: string | null
      tool_version?: string | null
    }
    export interface FinancialViabilityAnalysis {
      viability_score?: number | null
      budget_capacity_score?: number | null
      financial_health_score?: number | null
      sustainability_score?: number | null
      budget_implications?: string | null
      resource_requirements: Record<string, string>
      financial_risks: string[]
      financial_strategy?: string | null
      budget_recommendations: string[]
    }
    export interface GeographicAnalysis {
      primary_service_area?: string | null
      funder_geographic_focus?: string | null
      geographic_alignment_score?: number | null
      geographic_fit_assessment?: string | null
      regional_competition_analysis?: string | null
      location_advantages: string[]
      location_challenges: string[]
    }
    export interface HistoricalAnalysis {
      historical_grants: HistoricalGrant[]
      total_grants_analyzed?: number | null
      total_funding_amount?: number | null
      average_grant_size?: number | null
      typical_grant_range?: string | null
      funding_trends?: string | null
      geographic_patterns?: string | null
      similar_recipient_profiles: string[]
      success_factors: string[]
      competitive_intelligence?: string | null
    }
    export interface HistoricalGrant {
      recipient_name?: string | null
      grant_amount?: number | null
      grant_year?: number | null
      purpose?: string | null
      geographic_location?: string | null
    }
    export interface NetworkAnalysis {
      board_connections: BoardMember[]
      network_connections: NetworkConnection[]
      network_strength_score?: number | null
      relationship_advantages: string[]
      relationship_leverage_strategy?: string | null
      key_contacts_to_cultivate: string[]
    }
    export interface NetworkConnection {
      connection_type?: string | null
      connected_entity?: string | null
      strength?: number | null
      description?: string | null
    }
    export interface OperationalReadinessAnalysis {
      readiness_score?: number | null
      capacity_score?: number | null
      timeline_feasibility_score?: number | null
      infrastructure_readiness_score?: number | null
      capacity_gaps: string[]
      infrastructure_requirements: string[]
      timeline_challenges: string[]
      capacity_building_plan?: string | null
      operational_recommendations: string[]
      estimated_preparation_time_weeks?: number | null
    }
    export interface PolicyAlignment {
      relevant_policies: string[]
      alignment_score?: number | null
      policy_opportunities: string[]
      policy_risks: string[]
    }
    export interface PolicyAnalysis {
      federal_policy_alignment?: PolicyAlignment | null
      state_policy_alignment?: PolicyAlignment | null
      policy_landscape_summary?: string | null
      policy_opportunities: string[]
      advocacy_recommendations: string[]
    }
    export interface RelationshipMap {
      direct_relationships: string[]
      indirect_relationships: string[]
      partnership_opportunities: string[]
      relationship_insights?: string | null
      cultivation_strategy?: string | null
    }
    export interface RiskAssessment {
      overall_risk_level?: types.RiskLevel | null
      overall_risk_score?: number | null
      risk_factors: RiskFactor[]
      critical_risks: string[]
      manageable_risks: string[]
      risk_mitigation_plan?: string | null
    }
    export interface RiskFactor {
      category?: string | null
      risk_level?: types.RiskLevel | null
      description?: string | null
      impact?: string | null
      mitigation_strategy?: string | null
      probability?: number | null
    }
    export interface StrategicConsultingInsights {
      executive_summary?: string | null
      competitive_positioning?: string | null
      differentiation_strategy?: string | null
      multi_year_funding_strategy?: string | null
      partnership_development_strategy?: string | null
      capacity_building_roadmap?: string | null
      immediate_actions: string[]
      medium_term_actions: string[]
      long_term_actions: string[]
    }
    export interface StrategicFitAnalysis {
      fit_score?: number | null
      mission_alignment_score?: number | null
      program_alignment_score?: number | null
      geographic_alignment_score?: number | null
      alignment_strengths: string[]
      alignment_concerns: string[]
      strategic_rationale?: string | null
      strategic_positioning?: string | null
      key_differentiators: string[]
    }
}