/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    BoardMember: ClassViewer<'BoardMember', "name" | "title" | "affiliations" | "influence_score">;
    
    DeepIntelligenceOutput: ClassViewer<'DeepIntelligenceOutput', "strategic_fit" | "financial_viability" | "operational_readiness" | "risk_assessment" | "proceed_recommendation" | "success_probability" | "overall_score" | "executive_summary" | "key_strengths" | "key_challenges" | "recommended_next_steps" | "historical_intelligence" | "geographic_analysis" | "network_intelligence" | "relationship_mapping" | "policy_analysis" | "strategic_consulting" | "depth_executed" | "processing_time_seconds" | "api_cost_usd" | "timestamp" | "tool_version">;
    
    FinancialViabilityAnalysis: ClassViewer<'FinancialViabilityAnalysis', "viability_score" | "budget_capacity_score" | "financial_health_score" | "sustainability_score" | "budget_implications" | "resource_requirements" | "financial_risks" | "financial_strategy" | "budget_recommendations">;
    
    GeographicAnalysis: ClassViewer<'GeographicAnalysis', "primary_service_area" | "funder_geographic_focus" | "geographic_alignment_score" | "geographic_fit_assessment" | "regional_competition_analysis" | "location_advantages" | "location_challenges">;
    
    HistoricalAnalysis: ClassViewer<'HistoricalAnalysis', "historical_grants" | "total_grants_analyzed" | "total_funding_amount" | "average_grant_size" | "typical_grant_range" | "funding_trends" | "geographic_patterns" | "similar_recipient_profiles" | "success_factors" | "competitive_intelligence">;
    
    HistoricalGrant: ClassViewer<'HistoricalGrant', "recipient_name" | "grant_amount" | "grant_year" | "purpose" | "geographic_location">;
    
    NetworkAnalysis: ClassViewer<'NetworkAnalysis', "board_connections" | "network_connections" | "network_strength_score" | "relationship_advantages" | "relationship_leverage_strategy" | "key_contacts_to_cultivate">;
    
    NetworkConnection: ClassViewer<'NetworkConnection', "connection_type" | "connected_entity" | "strength" | "description">;
    
    OperationalReadinessAnalysis: ClassViewer<'OperationalReadinessAnalysis', "readiness_score" | "capacity_score" | "timeline_feasibility_score" | "infrastructure_readiness_score" | "capacity_gaps" | "infrastructure_requirements" | "timeline_challenges" | "capacity_building_plan" | "operational_recommendations" | "estimated_preparation_time_weeks">;
    
    PolicyAlignment: ClassViewer<'PolicyAlignment', "relevant_policies" | "alignment_score" | "policy_opportunities" | "policy_risks">;
    
    PolicyAnalysis: ClassViewer<'PolicyAnalysis', "federal_policy_alignment" | "state_policy_alignment" | "policy_landscape_summary" | "policy_opportunities" | "advocacy_recommendations">;
    
    RelationshipMap: ClassViewer<'RelationshipMap', "direct_relationships" | "indirect_relationships" | "partnership_opportunities" | "relationship_insights" | "cultivation_strategy">;
    
    RiskAssessment: ClassViewer<'RiskAssessment', "overall_risk_level" | "overall_risk_score" | "risk_factors" | "critical_risks" | "manageable_risks" | "risk_mitigation_plan">;
    
    RiskFactor: ClassViewer<'RiskFactor', "category" | "risk_level" | "description" | "impact" | "mitigation_strategy" | "probability">;
    
    StrategicConsultingInsights: ClassViewer<'StrategicConsultingInsights', "executive_summary" | "competitive_positioning" | "differentiation_strategy" | "multi_year_funding_strategy" | "partnership_development_strategy" | "capacity_building_roadmap" | "immediate_actions" | "medium_term_actions" | "long_term_actions">;
    
    StrategicFitAnalysis: ClassViewer<'StrategicFitAnalysis', "fit_score" | "mission_alignment_score" | "program_alignment_score" | "geographic_alignment_score" | "alignment_strengths" | "alignment_concerns" | "strategic_rationale" | "strategic_positioning" | "key_differentiators">;
    
    
    AnalysisDepth: EnumViewer<'AnalysisDepth', "ESSENTIALS" | "PREMIUM" | "QUICK" | "STANDARD" | "ENHANCED" | "COMPLETE">;
    
    RiskLevel: EnumViewer<'RiskLevel', "LOW" | "MEDIUM" | "HIGH" | "CRITICAL">;
    
    SuccessProbability: EnumViewer<'SuccessProbability', "VERY_LOW" | "LOW" | "MODERATE" | "HIGH" | "VERY_HIGH">;
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "BoardMember","DeepIntelligenceOutput","FinancialViabilityAnalysis","GeographicAnalysis","HistoricalAnalysis","HistoricalGrant","NetworkAnalysis","NetworkConnection","OperationalReadinessAnalysis","PolicyAlignment","PolicyAnalysis","RelationshipMap","RiskAssessment","RiskFactor","StrategicConsultingInsights","StrategicFitAnalysis",
          ]),
          enums: new Set([
            "AnalysisDepth","RiskLevel","SuccessProbability",
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.BoardMember = this.tb.classViewer("BoardMember", [
          "name","title","affiliations","influence_score",
        ]);
        
        this.DeepIntelligenceOutput = this.tb.classViewer("DeepIntelligenceOutput", [
          "strategic_fit","financial_viability","operational_readiness","risk_assessment","proceed_recommendation","success_probability","overall_score","executive_summary","key_strengths","key_challenges","recommended_next_steps","historical_intelligence","geographic_analysis","network_intelligence","relationship_mapping","policy_analysis","strategic_consulting","depth_executed","processing_time_seconds","api_cost_usd","timestamp","tool_version",
        ]);
        
        this.FinancialViabilityAnalysis = this.tb.classViewer("FinancialViabilityAnalysis", [
          "viability_score","budget_capacity_score","financial_health_score","sustainability_score","budget_implications","resource_requirements","financial_risks","financial_strategy","budget_recommendations",
        ]);
        
        this.GeographicAnalysis = this.tb.classViewer("GeographicAnalysis", [
          "primary_service_area","funder_geographic_focus","geographic_alignment_score","geographic_fit_assessment","regional_competition_analysis","location_advantages","location_challenges",
        ]);
        
        this.HistoricalAnalysis = this.tb.classViewer("HistoricalAnalysis", [
          "historical_grants","total_grants_analyzed","total_funding_amount","average_grant_size","typical_grant_range","funding_trends","geographic_patterns","similar_recipient_profiles","success_factors","competitive_intelligence",
        ]);
        
        this.HistoricalGrant = this.tb.classViewer("HistoricalGrant", [
          "recipient_name","grant_amount","grant_year","purpose","geographic_location",
        ]);
        
        this.NetworkAnalysis = this.tb.classViewer("NetworkAnalysis", [
          "board_connections","network_connections","network_strength_score","relationship_advantages","relationship_leverage_strategy","key_contacts_to_cultivate",
        ]);
        
        this.NetworkConnection = this.tb.classViewer("NetworkConnection", [
          "connection_type","connected_entity","strength","description",
        ]);
        
        this.OperationalReadinessAnalysis = this.tb.classViewer("OperationalReadinessAnalysis", [
          "readiness_score","capacity_score","timeline_feasibility_score","infrastructure_readiness_score","capacity_gaps","infrastructure_requirements","timeline_challenges","capacity_building_plan","operational_recommendations","estimated_preparation_time_weeks",
        ]);
        
        this.PolicyAlignment = this.tb.classViewer("PolicyAlignment", [
          "relevant_policies","alignment_score","policy_opportunities","policy_risks",
        ]);
        
        this.PolicyAnalysis = this.tb.classViewer("PolicyAnalysis", [
          "federal_policy_alignment","state_policy_alignment","policy_landscape_summary","policy_opportunities","advocacy_recommendations",
        ]);
        
        this.RelationshipMap = this.tb.classViewer("RelationshipMap", [
          "direct_relationships","indirect_relationships","partnership_opportunities","relationship_insights","cultivation_strategy",
        ]);
        
        this.RiskAssessment = this.tb.classViewer("RiskAssessment", [
          "overall_risk_level","overall_risk_score","risk_factors","critical_risks","manageable_risks","risk_mitigation_plan",
        ]);
        
        this.RiskFactor = this.tb.classViewer("RiskFactor", [
          "category","risk_level","description","impact","mitigation_strategy","probability",
        ]);
        
        this.StrategicConsultingInsights = this.tb.classViewer("StrategicConsultingInsights", [
          "executive_summary","competitive_positioning","differentiation_strategy","multi_year_funding_strategy","partnership_development_strategy","capacity_building_roadmap","immediate_actions","medium_term_actions","long_term_actions",
        ]);
        
        this.StrategicFitAnalysis = this.tb.classViewer("StrategicFitAnalysis", [
          "fit_score","mission_alignment_score","program_alignment_score","geographic_alignment_score","alignment_strengths","alignment_concerns","strategic_rationale","strategic_positioning","key_differentiators",
        ]);
        
        
        this.AnalysisDepth = this.tb.enumViewer("AnalysisDepth", [
          "ESSENTIALS","PREMIUM","QUICK","STANDARD","ENHANCED","COMPLETE",
        ]);
        
        this.RiskLevel = this.tb.enumViewer("RiskLevel", [
          "LOW","MEDIUM","HIGH","CRITICAL",
        ]);
        
        this.SuccessProbability = this.tb.enumViewer("SuccessProbability", [
          "VERY_LOW","LOW","MODERATE","HIGH","VERY_HIGH",
        ]);
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}