#!/usr/bin/env python3
"""
Local GitHub CLI Setup and Configuration Script
Sets up GitHub CLI for local-only bug tracking and issue management.

This script:
1. Checks for GitHub CLI installation
2. Configures local repository for issue tracking
3. Sets up issue templates and labels
4. Creates local project structure
5. Configures GitHub CLI for offline operation
"""

import os
import subprocess
import sys
import json
from pathlib import Path
from typing import Dict, List, Any, Optional

class LocalGitHubCLISetup:
    """Setup and configure GitHub CLI for local bug tracking"""

    def __init__(self):
        self.project_root = Path(__file__).parent.parent
        self.github_dir = self.project_root / ".github"
        self.issue_templates_dir = self.github_dir / "ISSUE_TEMPLATE"

    def check_github_cli_installation(self) -> bool:
        """Check if GitHub CLI is installed"""
        try:
            result = subprocess.run(["gh", "--version"], capture_output=True, text=True)
            if result.returncode == 0:
                print(f"GitHub CLI found: {result.stdout.strip()}")
                return True
            else:
                print("GitHub CLI not found")
                return False
        except FileNotFoundError:
            print("GitHub CLI not installed")
            return False

    def install_github_cli_windows(self) -> bool:
        """Install GitHub CLI on Windows using winget"""
        print("Installing GitHub CLI using winget...")
        try:
            result = subprocess.run(
                ["winget", "install", "GitHub.cli"],
                capture_output=True,
                text=True,
                timeout=300
            )
            if result.returncode == 0:
                print("GitHub CLI installed successfully")
                return True
            else:
                print(f"GitHub CLI installation failed: {result.stderr}")
                return False
        except Exception as e:
            print(f"GitHub CLI installation error: {str(e)}")
            return False

    def setup_github_directory_structure(self):
        """Create GitHub directory structure for local repository"""
        print("Setting up GitHub directory structure...")

        # Create .github directory structure
        self.github_dir.mkdir(exist_ok=True)
        self.issue_templates_dir.mkdir(exist_ok=True)

        print(f"Created directory: {self.github_dir}")
        print(f"Created directory: {self.issue_templates_dir}")

    def create_bug_issue_template(self):
        """Create automated bug issue template"""
        print("Creating automated bug issue template...")

        template_content = """---
name: Automated Bug Report
about: Automatically generated bug report from testing framework
title: '[BUG] {{title}}'
labels: 'bug, automated'
assignees: ''

---

## Bug Information
- **Bug ID**: {{bug_id}}
- **Severity**: {{severity}}
- **Category**: {{category}}
- **Source Test**: {{source_test}}
- **Created**: {{created_at}}

## Description
{{description}}

## Reproduction Steps
{{reproduction_steps}}

## Expected Behavior
The system should function without errors and meet all test requirements.

## Additional Context
- **Estimated Effort**: {{estimated_effort}} hours
- **Assigned Subagents**: {{assigned_subagents}}
- **Test Framework**: Catalynx Integrated Testing

## Technical Details
```
{{technical_details}}
```

## Resolution Tracking
- [ ] Issue assigned to appropriate subagent
- [ ] Root cause identified
- [ ] Fix implemented
- [ ] Fix reviewed and approved
- [ ] Regression tests added
- [ ] Fix verified with testing framework
- [ ] Issue closed

---
*This issue was automatically generated by the Catalynx Integrated Testing Framework*
"""

        template_file = self.issue_templates_dir / "automated-bug.md"
        with open(template_file, 'w', encoding='utf-8') as f:
            f.write(template_content)

        print(f"Created bug issue template: {template_file}")

    def create_github_labels_config(self):
        """Create GitHub labels configuration for bug tracking"""
        print("Creating GitHub labels configuration...")

        labels = [
            # Severity labels
            {"name": "bug-critical", "color": "d73a4a", "description": "Critical bugs blocking release"},
            {"name": "bug-high", "color": "ff6b6b", "description": "High priority bugs"},
            {"name": "bug-medium", "color": "ff9f43", "description": "Medium priority bugs"},
            {"name": "bug-low", "color": "feca57", "description": "Low priority bugs"},

            # Category labels
            {"name": "bug-frontend", "color": "0052cc", "description": "Frontend UI/UX issues"},
            {"name": "bug-backend", "color": "5319e7", "description": "Backend API/processor issues"},
            {"name": "bug-integration", "color": "1d76db", "description": "Integration between systems"},
            {"name": "bug-performance", "color": "d4c5f9", "description": "Performance related issues"},
            {"name": "bug-data", "color": "0e8a16", "description": "Data processing issues"},
            {"name": "bug-security", "color": "d93f0b", "description": "Security related issues"},
            {"name": "bug-documentation", "color": "c2e0c6", "description": "Documentation issues"},

            # Status labels
            {"name": "status-identified", "color": "fbca04", "description": "Bug identified by testing"},
            {"name": "status-assigned", "color": "0052cc", "description": "Bug assigned to subagent"},
            {"name": "status-in-progress", "color": "1d76db", "description": "Bug being worked on"},
            {"name": "status-fixed", "color": "28a745", "description": "Bug fixed, pending verification"},
            {"name": "status-verified", "color": "0e8a16", "description": "Bug fix verified"},

            # Subagent labels
            {"name": "subagent-frontend", "color": "0052cc", "description": "Assigned to frontend specialist"},
            {"name": "subagent-ux-ui", "color": "1d76db", "description": "Assigned to UX/UI specialist"},
            {"name": "subagent-code-review", "color": "5319e7", "description": "Assigned to code reviewer"},
            {"name": "subagent-testing", "color": "28a745", "description": "Assigned to testing expert"},
            {"name": "subagent-performance", "color": "d4c5f9", "description": "Assigned to performance optimizer"},
            {"name": "subagent-documentation", "color": "c2e0c6", "description": "Assigned to documentation specialist"},

            # Special labels
            {"name": "automated", "color": "f9ca24", "description": "Automatically generated"},
            {"name": "version-1-blocker", "color": "d73a4a", "description": "Blocks Version 1 release"},
            {"name": "real-data-issue", "color": "0e8a16", "description": "Issue with real data processing"}
        ]

        labels_file = self.github_dir / "labels.json"
        with open(labels_file, 'w', encoding='utf-8') as f:
            json.dump(labels, f, indent=2)

        print(f"Created labels configuration: {labels_file}")
        return labels

    def initialize_local_repository(self):
        """Initialize local repository for GitHub CLI usage"""
        print("Initializing local repository for GitHub CLI...")

        try:
            # Check if already a git repository
            result = subprocess.run(
                ["git", "status"],
                cwd=self.project_root,
                capture_output=True,
                text=True
            )

            if result.returncode == 0:
                print("Repository already initialized")
            else:
                # Initialize git repository
                subprocess.run(["git", "init"], cwd=self.project_root, check=True)
                print("Git repository initialized")

                # Add initial commit if needed
                subprocess.run(["git", "add", "."], cwd=self.project_root)
                subprocess.run(
                    ["git", "commit", "-m", "Initial commit for GitHub CLI integration"],
                    cwd=self.project_root
                )
                print("Initial commit created")

        except subprocess.CalledProcessError as e:
            print(f"Git initialization warning: {e}")

    def configure_github_cli_local_mode(self):
        """Configure GitHub CLI for local-only operation"""
        print("Configuring GitHub CLI for local operation...")

        # Create GitHub CLI configuration directory
        gh_config_dir = Path.home() / ".config" / "gh"
        gh_config_dir.mkdir(parents=True, exist_ok=True)

        # Create local configuration for offline/local usage
        config = {
            "version": "1",
            "hosts": {
                "localhost": {
                    "user": "local-user",
                    "oauth_token": "local-token",
                    "git_protocol": "https"
                }
            },
            "editor": "code",
            "prompt": "enabled",
            "pager": "less"
        }

        config_file = gh_config_dir / "config.yml"

        # Convert to YAML format manually (simpler than importing yaml)
        yaml_content = f"""version: {config['version']}
hosts:
  localhost:
    user: {config['hosts']['localhost']['user']}
    oauth_token: {config['hosts']['localhost']['oauth_token']}
    git_protocol: {config['hosts']['localhost']['git_protocol']}
editor: {config['editor']}
prompt: {config['prompt']}
pager: {config['pager']}
"""

        with open(config_file, 'w', encoding='utf-8') as f:
            f.write(yaml_content)

        print(f"GitHub CLI configuration created: {config_file}")

    def create_local_issue_database_structure(self):
        """Create local issue database structure"""
        print("Creating local issue database structure...")

        # Create issues directory for local storage
        issues_dir = self.project_root / ".github" / "issues"
        issues_dir.mkdir(exist_ok=True)

        # Create issues database schema
        schema = {
            "issues": {},
            "next_issue_id": 1,
            "labels": [],
            "milestones": [
                {
                    "id": 1,
                    "title": "Version 1 Release",
                    "description": "Issues blocking Version 1 production release",
                    "state": "open",
                    "created_at": "2025-01-19T00:00:00Z"
                }
            ],
            "project_boards": [
                {
                    "id": 1,
                    "name": "Bug Resolution Workflow",
                    "columns": [
                        "Identified",
                        "Assigned",
                        "In Progress",
                        "Review",
                        "Verified",
                        "Closed"
                    ]
                }
            ]
        }

        db_file = issues_dir / "local_issues_db.json"
        with open(db_file, 'w', encoding='utf-8') as f:
            json.dump(schema, f, indent=2)

        print(f"Local issue database created: {db_file}")

    def create_github_cli_scripts(self):
        """Create helper scripts for GitHub CLI operations"""
        print("Creating GitHub CLI helper scripts...")

        scripts_dir = self.project_root / "scripts" / "github_cli"
        scripts_dir.mkdir(exist_ok=True)

        # Create issue creation script
        create_issue_script = """#!/bin/bash
# Helper script for creating issues with GitHub CLI
# Usage: ./create_issue.sh "Title" "Body" "labels"

TITLE="$1"
BODY="$2"
LABELS="$3"

if [ -z "$TITLE" ]; then
    echo "Usage: $0 'Issue Title' 'Issue Body' 'label1,label2'"
    exit 1
fi

# Create issue using GitHub CLI
gh issue create \\
    --title "$TITLE" \\
    --body "$BODY" \\
    --label "$LABELS" \\
    --assignee "@me"

echo "Issue created successfully"
"""

        script_file = scripts_dir / "create_issue.sh"
        with open(script_file, 'w', encoding='utf-8') as f:
            f.write(create_issue_script)

        # Create Windows batch version
        batch_script = """@echo off
REM Helper script for creating issues with GitHub CLI
REM Usage: create_issue.bat "Title" "Body" "labels"

set TITLE=%1
set BODY=%2
set LABELS=%3

if "%TITLE%"=="" (
    echo Usage: %0 "Issue Title" "Issue Body" "label1,label2"
    exit /b 1
)

REM Create issue using GitHub CLI
gh issue create --title %TITLE% --body %BODY% --label %LABELS% --assignee "@me"

echo Issue created successfully
"""

        batch_file = scripts_dir / "create_issue.bat"
        with open(batch_file, 'w', encoding='utf-8') as f:
            f.write(batch_script)

        print(f"GitHub CLI scripts created: {scripts_dir}")

    def setup_complete_local_github_environment(self) -> bool:
        """Complete setup of local GitHub CLI environment"""
        print("Setting up complete local GitHub CLI environment...")
        print("=" * 60)

        success = True

        try:
            # Step 1: Check GitHub CLI installation
            if not self.check_github_cli_installation():
                print("GitHub CLI not found. Installing...")
                if not self.install_github_cli_windows():
                    print("Failed to install GitHub CLI automatically.")
                    print("Please install manually:")
                    print("   - Download from: https://cli.github.com/")
                    print("   - Or use: winget install GitHub.cli")
                    print("Continuing with repository setup...")
                    # Continue setup even without GitHub CLI

            # Step 2: Setup directory structure
            self.setup_github_directory_structure()

            # Step 3: Create issue templates
            self.create_bug_issue_template()

            # Step 4: Create labels configuration
            labels = self.create_github_labels_config()

            # Step 5: Initialize repository
            self.initialize_local_repository()

            # Step 6: Configure GitHub CLI
            self.configure_github_cli_local_mode()

            # Step 7: Create local issue database
            self.create_local_issue_database_structure()

            # Step 8: Create helper scripts
            self.create_github_cli_scripts()

            print("\n" + "=" * 60)
            print("LOCAL GITHUB CLI SETUP COMPLETE")
            print("=" * 60)
            print("Repository root:", self.project_root)
            print("GitHub directory:", self.github_dir)
            print("Labels configured:", len(labels))
            print("Issue templates created")
            print("Helper scripts available")
            print("\nReady for automated bug tracking with GitHub CLI!")

        except Exception as e:
            print(f"\nSetup failed: {str(e)}")
            success = False

        return success

def main():
    """Main setup function"""
    print("Catalynx Local GitHub CLI Setup")
    print("Setting up local GitHub CLI for automated bug tracking")
    print("=" * 60)

    setup = LocalGitHubCLISetup()

    try:
        success = setup.setup_complete_local_github_environment()

        if success:
            print("\nSetup completed successfully!")
            print("\nNext steps:")
            print("1. Test GitHub CLI: gh --version")
            print("2. Create a test issue: gh issue create --title 'Test Issue'")
            print("3. List issues: gh issue list")
            print("4. Run integrated testing framework to see automatic issue creation")
            return 0
        else:
            print("\n❌ Setup incomplete. Please review errors above.")
            return 1

    except KeyboardInterrupt:
        print("\nSetup interrupted by user")
        return 1
    except Exception as e:
        print(f"\nSetup failed with error: {str(e)}")
        return 1

if __name__ == "__main__":
    exit_code = main()
    sys.exit(exit_code)