/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, BamlCtxManager, ClientRegistry, Image, Audio, Pdf, Video, FunctionLog } from
"@boundaryml/baml"
import { toBamlError, HTTPRequest } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type * as types from "./types"
import type {BorderProximity, BorderProximityAnalysis, BundledGrantee, CapacityLevel, CoFundingAnalysisInput, CoFundingAnalysisOutput, CompositeScoreResult, ExpertDecision, FilingRecencyAnalysis, FilingRecencyLevel, FoundationOpportunityData, FoundationOverlap, FunderRecommendation, FunderSimilarity, FundingSource, FundingStability, GrantHistoryAnalysis, GrantHistoryStatus, GrantSizeAnalysis, GrantSizeBand, GrantSizeFit, GranteeBundlingInput, GranteeBundlingOutput, NTEECode, NTEEDataSource, NTEEMatchLevel, NTEEScoreResult, NTEEVoteResult, PeerFunderGroup, RecipientVote, RecommendationType, ReliabilitySafeguardsResult, ScheduleIAnalysis, ThematicCluster, TriageItem, TriagePriority, TriageQueueStats, TriageStatus} from "./types"
import type TypeBuilder from "./type_builder"

type TickReason = "Unknown";

type BamlCallOptions = {
tb?: TypeBuilder
clientRegistry?: ClientRegistry
env?: Record<string, string | undefined>
  onTick?: (reason: TickReason, log: FunctionLog | null) => void
  }

  export class AsyncHttpRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
      }

      export class AsyncHttpStreamRequest {
      constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

      
          }