/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  BorderProximity,  BorderProximityAnalysis,  BundledGrantee,  CapacityLevel,  CoFundingAnalysisInput,  CoFundingAnalysisOutput,  CompositeScoreResult,  ExpertDecision,  FilingRecencyAnalysis,  FilingRecencyLevel,  FoundationOpportunityData,  FoundationOverlap,  FunderRecommendation,  FunderSimilarity,  FundingSource,  FundingStability,  GrantHistoryAnalysis,  GrantHistoryStatus,  GrantSizeAnalysis,  GrantSizeBand,  GrantSizeFit,  GranteeBundlingInput,  GranteeBundlingOutput,  NTEECode,  NTEEDataSource,  NTEEMatchLevel,  NTEEScoreResult,  NTEEVoteResult,  PeerFunderGroup,  RecipientVote,  RecommendationType,  ReliabilitySafeguardsResult,  ScheduleIAnalysis,  ThematicCluster,  TriageItem,  TriagePriority,  TriageQueueStats,  TriageStatus } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface BorderProximityAnalysis {
      distance_to_border_miles?: number | null
      nearest_border_state?: string | null
      proximity_level?: types.BorderProximity | null
      proximity_score?: number | null
      boost?: number | null
      explanation?: string | null
      cross_border_eligible?: boolean | null
    }
    export interface BundledGrantee {
      grantee_ein?: string | null
      grantee_name?: string | null
      normalized_name?: string | null
      funder_count?: number | null
      total_funding?: number | null
      average_grant_size?: number | null
      funding_sources: FundingSource[]
      first_grant_year?: number | null
      last_grant_year?: number | null
      funding_consistency?: number | null
      geographic_location?: string | null
      common_purposes: string[]
      purpose_diversity_score?: number | null
      funding_stability?: types.FundingStability | null
      co_funding_strength?: number | null
    }
    export interface CoFundingAnalysisInput {
      bundling_results?: string | null
      similarity_threshold?: number | null
      max_peer_funders?: number | null
      include_network_graph?: boolean | null
    }
    export interface CoFundingAnalysisOutput {
      funder_similarity_pairs: FunderSimilarity[]
      highly_similar_pairs: FunderSimilarity[]
      peer_funder_groups: PeerFunderGroup[]
      foundation_network_graph?: Record<string, string> | null
      network_statistics: Record<string, string>
      recommendations: FunderRecommendation[]
      processing_time_seconds?: number | null
      analysis_date?: string | null
    }
    export interface CompositeScoreResult {
      final_score?: number | null
      recommendation?: string | null
      ntee_alignment_score?: number | null
      geographic_match_score?: number | null
      recipient_coherence_score?: number | null
      financial_capacity_score?: number | null
      grant_size_fit_score?: number | null
      application_policy_score?: number | null
      filing_recency_score?: number | null
      foundation_type_score?: number | null
      coherence_boost?: number | null
      time_decay_penalty?: number | null
      ntee_explanation?: string | null
      confidence?: number | null
      should_abstain?: boolean | null
      schedule_i_analysis?: Record<string, string> | null
      grant_size_analysis?: Record<string, string> | null
      abstain_reason?: string | null
    }
    export interface FilingRecencyAnalysis {
      tax_year?: number | null
      years_ago?: number | null
      recency_level?: types.FilingRecencyLevel | null
      recency_score?: number | null
      penalty?: number | null
      explanation?: string | null
      warning?: string | null
    }
    export interface FoundationOpportunityData {
      foundation_ein?: string | null
      foundation_name?: string | null
      ntee_codes: string[]
      ntee_code_sources: Record<string, string>
      ntee_code_dates?: Record<string, string> | null
      schedule_i_grantees?: string | null
      typical_grant_amount?: number | null
      grant_amount_min?: number | null
      grant_amount_max?: number | null
      geographic_focus_states: string[]
      total_assets?: number | null
      grants_paid_total?: number | null
      accepts_applications?: boolean | null
      most_recent_filing_year?: number | null
    }
    export interface FoundationOverlap {
      foundation_ein_1?: string | null
      foundation_name_1?: string | null
      foundation_ein_2?: string | null
      foundation_name_2?: string | null
      shared_grantees_count?: number | null
      shared_grantee_eins: string[]
      total_overlap_funding?: number | null
      jaccard_similarity?: number | null
      overlap_percentage_1?: number | null
      overlap_percentage_2?: number | null
    }
    export interface FunderRecommendation {
      recommended_foundation_ein?: string | null
      recommended_foundation_name?: string | null
      recommendation_type?: types.RecommendationType | null
      rationale?: string | null
      confidence_score?: number | null
      supporting_evidence: string[]
      shared_funders: string[]
      similarity_to_current_funders?: number | null
      estimated_grant_range?: string | null
      suggested_approach?: string | null
      priority?: string | null
    }
    export interface FunderSimilarity {
      foundation_ein_1?: string | null
      foundation_name_1?: string | null
      foundation_ein_2?: string | null
      foundation_name_2?: string | null
      similarity_score?: number | null
      jaccard_similarity?: number | null
      shared_grantees_count?: number | null
      total_co_funding_amount?: number | null
      average_co_grant_size?: number | null
      recency_score?: number | null
      funding_years_overlap: number[]
      shared_grantees: string[]
      common_geographic_focus?: string | null
      common_thematic_focus: string[]
    }
    export interface FundingSource {
      foundation_ein?: string | null
      foundation_name?: string | null
      grant_amount?: number | null
      grant_year?: number | null
      grant_purpose?: string | null
      grant_tier?: string | null
    }
    export interface GrantHistoryAnalysis {
      years_of_grants?: number | null
      total_grants?: number | null
      avg_grants_per_year?: number | null
      history_status?: types.GrantHistoryStatus | null
      history_score?: number | null
      penalty?: number | null
      is_mirage?: boolean | null
      explanation?: string | null
      recommendation?: string | null
    }
    export interface GrantSizeAnalysis {
      grant_amount?: number | null
      org_revenue?: number | null
      grant_size_band?: types.GrantSizeBand | null
      capacity_level?: types.CapacityLevel | null
      grant_to_revenue_ratio?: number | null
      fit_level?: types.GrantSizeFit | null
      fit_score?: number | null
      multiplier?: number | null
      explanation?: string | null
      recommendations?: string | null
    }
    export interface GranteeBundlingInput {
      foundation_eins: string[]
      tax_years: number[]
      min_foundations?: number | null
      include_grant_purposes?: boolean | null
      geographic_filter?: string[] | null
      min_grant_amount?: number | null
      normalize_recipient_names?: boolean | null
      fuzzy_matching_threshold?: number | null
    }
    export interface GranteeBundlingOutput {
      total_foundations_analyzed?: number | null
      foundation_eins: string[]
      tax_years_analyzed: number[]
      total_unique_grantees?: number | null
      bundled_grantees: BundledGrantee[]
      single_funder_grantees_count?: number | null
      foundation_overlap_matrix: FoundationOverlap[]
      top_co_funded_orgs: BundledGrantee[]
      thematic_clusters: ThematicCluster[]
      total_grants_analyzed?: number | null
      total_funding_amount?: number | null
      average_grants_per_foundation?: number | null
      average_grantees_per_foundation?: number | null
      data_completeness_score?: number | null
      recipient_matching_confidence?: number | null
      processing_time_seconds?: number | null
      analysis_date?: string | null
      api_cost_usd?: number | null
    }
    export interface NTEECode {
      full_code?: string | null
      major?: string | null
      leaf?: string | null
      source?: types.NTEEDataSource | null
      source_date?: string | null
      confidence?: number | null
    }
    export interface NTEEScoreResult {
      score?: number | null
      match_level?: types.NTEEMatchLevel | null
      profile_codes: NTEECode[]
      foundation_codes: NTEECode[]
      major_score?: number | null
      leaf_score?: number | null
      time_decay_factor?: number | null
      confidence?: number | null
      explanation?: string | null
      weighted_score?: number | null
    }
    export interface NTEEVoteResult {
      ntee_code?: string | null
      total_votes?: number | null
      vote_count?: number | null
      total_grant_amount?: number | null
      avg_grant_amount?: number | null
      recipients: string[]
    }
    export interface PeerFunderGroup {
      cluster_id?: string | null
      cluster_name?: string | null
      member_foundations: string[]
      member_count?: number | null
      shared_focus_areas: string[]
      geographic_concentration?: string | null
      average_grant_size?: number | null
      total_cluster_funding?: number | null
      cluster_density?: number | null
      bridge_foundations: string[]
    }
    export interface RecipientVote {
      recipient_name?: string | null
      recipient_ein?: string | null
      grant_amount?: number | null
      grant_year?: number | null
      ntee_codes: string[]
      ein_confidence?: string | null
      vote_weight?: number | null
    }
    export interface ReliabilitySafeguardsResult {
      filing_recency?: FilingRecencyAnalysis | null
      grant_history?: GrantHistoryAnalysis | null
      border_proximity?: BorderProximityAnalysis | null
      reliability_score?: number | null
      total_penalty?: number | null
      total_boost?: number | null
      net_adjustment?: number | null
      has_reliability_concerns?: boolean | null
      concerns: string[]
      overall_assessment?: string | null
      recommendation?: string | null
    }
    export interface ScheduleIAnalysis {
      foundation_ein?: string | null
      total_recipients?: number | null
      total_grant_amount?: number | null
      analysis_years: number[]
      ntee_votes: Record<string, NTEEVoteResult>
      top_ntee_codes: string[]
      coherence_score?: number | null
      entropy_score?: number | null
      concentration_ratio?: number | null
      ein_resolution_rate?: number | null
      high_confidence_rate?: number | null
      is_coherent?: boolean | null
      recommended_boost?: number | null
    }
    export interface ThematicCluster {
      cluster_id?: string | null
      cluster_name?: string | null
      grantee_count?: number | null
      total_funding?: number | null
      member_grantees: string[]
      common_keywords: string[]
      funding_foundations: string[]
    }
    export interface TriageItem {
      item_id?: string | null
      profile_ein?: string | null
      profile_name?: string | null
      foundation_ein?: string | null
      foundation_name?: string | null
      composite_score?: number | null
      confidence?: number | null
      abstain_reason?: string | null
      ntee_score?: number | null
      geographic_score?: number | null
      coherence_score?: number | null
      grant_size_score?: number | null
      status?: types.TriageStatus | null
      priority?: types.TriagePriority | null
      created_at?: string | null
      assigned_to?: string | null
      expert_decision?: types.ExpertDecision | null
      expert_rationale?: string | null
      reviewed_at?: string | null
      reviewed_by?: string | null
      notes: string[]
      tags: string[]
    }
    export interface TriageQueueStats {
      total_items?: number | null
      pending_count?: number | null
      in_review_count?: number | null
      approved_count?: number | null
      rejected_count?: number | null
      critical_count?: number | null
      high_count?: number | null
      medium_count?: number | null
      low_count?: number | null
      avg_review_time_hours?: number | null
      approval_rate?: number | null
      agreement_rate?: number | null
    }
}