/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    BorderProximityAnalysis: ClassViewer<'BorderProximityAnalysis', "distance_to_border_miles" | "nearest_border_state" | "proximity_level" | "proximity_score" | "boost" | "explanation" | "cross_border_eligible">;
    
    BundledGrantee: ClassViewer<'BundledGrantee', "grantee_ein" | "grantee_name" | "normalized_name" | "funder_count" | "total_funding" | "average_grant_size" | "funding_sources" | "first_grant_year" | "last_grant_year" | "funding_consistency" | "geographic_location" | "common_purposes" | "purpose_diversity_score" | "funding_stability" | "co_funding_strength">;
    
    CoFundingAnalysisInput: ClassViewer<'CoFundingAnalysisInput', "bundling_results" | "similarity_threshold" | "max_peer_funders" | "include_network_graph">;
    
    CoFundingAnalysisOutput: ClassViewer<'CoFundingAnalysisOutput', "funder_similarity_pairs" | "highly_similar_pairs" | "peer_funder_groups" | "foundation_network_graph" | "network_statistics" | "recommendations" | "processing_time_seconds" | "analysis_date">;
    
    CompositeScoreResult: ClassViewer<'CompositeScoreResult', "final_score" | "recommendation" | "ntee_alignment_score" | "geographic_match_score" | "recipient_coherence_score" | "financial_capacity_score" | "grant_size_fit_score" | "application_policy_score" | "filing_recency_score" | "foundation_type_score" | "coherence_boost" | "time_decay_penalty" | "ntee_explanation" | "confidence" | "should_abstain" | "schedule_i_analysis" | "grant_size_analysis" | "abstain_reason">;
    
    FilingRecencyAnalysis: ClassViewer<'FilingRecencyAnalysis', "tax_year" | "years_ago" | "recency_level" | "recency_score" | "penalty" | "explanation" | "warning">;
    
    FoundationOpportunityData: ClassViewer<'FoundationOpportunityData', "foundation_ein" | "foundation_name" | "ntee_codes" | "ntee_code_sources" | "ntee_code_dates" | "schedule_i_grantees" | "typical_grant_amount" | "grant_amount_min" | "grant_amount_max" | "geographic_focus_states" | "total_assets" | "grants_paid_total" | "accepts_applications" | "most_recent_filing_year">;
    
    FoundationOverlap: ClassViewer<'FoundationOverlap', "foundation_ein_1" | "foundation_name_1" | "foundation_ein_2" | "foundation_name_2" | "shared_grantees_count" | "shared_grantee_eins" | "total_overlap_funding" | "jaccard_similarity" | "overlap_percentage_1" | "overlap_percentage_2">;
    
    FunderRecommendation: ClassViewer<'FunderRecommendation', "recommended_foundation_ein" | "recommended_foundation_name" | "recommendation_type" | "rationale" | "confidence_score" | "supporting_evidence" | "shared_funders" | "similarity_to_current_funders" | "estimated_grant_range" | "suggested_approach" | "priority">;
    
    FunderSimilarity: ClassViewer<'FunderSimilarity', "foundation_ein_1" | "foundation_name_1" | "foundation_ein_2" | "foundation_name_2" | "similarity_score" | "jaccard_similarity" | "shared_grantees_count" | "total_co_funding_amount" | "average_co_grant_size" | "recency_score" | "funding_years_overlap" | "shared_grantees" | "common_geographic_focus" | "common_thematic_focus">;
    
    FundingSource: ClassViewer<'FundingSource', "foundation_ein" | "foundation_name" | "grant_amount" | "grant_year" | "grant_purpose" | "grant_tier">;
    
    GrantHistoryAnalysis: ClassViewer<'GrantHistoryAnalysis', "years_of_grants" | "total_grants" | "avg_grants_per_year" | "history_status" | "history_score" | "penalty" | "is_mirage" | "explanation" | "recommendation">;
    
    GrantSizeAnalysis: ClassViewer<'GrantSizeAnalysis', "grant_amount" | "org_revenue" | "grant_size_band" | "capacity_level" | "grant_to_revenue_ratio" | "fit_level" | "fit_score" | "multiplier" | "explanation" | "recommendations">;
    
    GranteeBundlingInput: ClassViewer<'GranteeBundlingInput', "foundation_eins" | "tax_years" | "min_foundations" | "include_grant_purposes" | "geographic_filter" | "min_grant_amount" | "normalize_recipient_names" | "fuzzy_matching_threshold">;
    
    GranteeBundlingOutput: ClassViewer<'GranteeBundlingOutput', "total_foundations_analyzed" | "foundation_eins" | "tax_years_analyzed" | "total_unique_grantees" | "bundled_grantees" | "single_funder_grantees_count" | "foundation_overlap_matrix" | "top_co_funded_orgs" | "thematic_clusters" | "total_grants_analyzed" | "total_funding_amount" | "average_grants_per_foundation" | "average_grantees_per_foundation" | "data_completeness_score" | "recipient_matching_confidence" | "processing_time_seconds" | "analysis_date" | "api_cost_usd">;
    
    NTEECode: ClassViewer<'NTEECode', "full_code" | "major" | "leaf" | "source" | "source_date" | "confidence">;
    
    NTEEScoreResult: ClassViewer<'NTEEScoreResult', "score" | "match_level" | "profile_codes" | "foundation_codes" | "major_score" | "leaf_score" | "time_decay_factor" | "confidence" | "explanation" | "weighted_score">;
    
    NTEEVoteResult: ClassViewer<'NTEEVoteResult', "ntee_code" | "total_votes" | "vote_count" | "total_grant_amount" | "avg_grant_amount" | "recipients">;
    
    PeerFunderGroup: ClassViewer<'PeerFunderGroup', "cluster_id" | "cluster_name" | "member_foundations" | "member_count" | "shared_focus_areas" | "geographic_concentration" | "average_grant_size" | "total_cluster_funding" | "cluster_density" | "bridge_foundations">;
    
    RecipientVote: ClassViewer<'RecipientVote', "recipient_name" | "recipient_ein" | "grant_amount" | "grant_year" | "ntee_codes" | "ein_confidence" | "vote_weight">;
    
    ReliabilitySafeguardsResult: ClassViewer<'ReliabilitySafeguardsResult', "filing_recency" | "grant_history" | "border_proximity" | "reliability_score" | "total_penalty" | "total_boost" | "net_adjustment" | "has_reliability_concerns" | "concerns" | "overall_assessment" | "recommendation">;
    
    ScheduleIAnalysis: ClassViewer<'ScheduleIAnalysis', "foundation_ein" | "total_recipients" | "total_grant_amount" | "analysis_years" | "ntee_votes" | "top_ntee_codes" | "coherence_score" | "entropy_score" | "concentration_ratio" | "ein_resolution_rate" | "high_confidence_rate" | "is_coherent" | "recommended_boost">;
    
    ThematicCluster: ClassViewer<'ThematicCluster', "cluster_id" | "cluster_name" | "grantee_count" | "total_funding" | "member_grantees" | "common_keywords" | "funding_foundations">;
    
    TriageItem: ClassViewer<'TriageItem', "item_id" | "profile_ein" | "profile_name" | "foundation_ein" | "foundation_name" | "composite_score" | "confidence" | "abstain_reason" | "ntee_score" | "geographic_score" | "coherence_score" | "grant_size_score" | "status" | "priority" | "created_at" | "assigned_to" | "expert_decision" | "expert_rationale" | "reviewed_at" | "reviewed_by" | "notes" | "tags">;
    
    TriageQueueStats: ClassViewer<'TriageQueueStats', "total_items" | "pending_count" | "in_review_count" | "approved_count" | "rejected_count" | "critical_count" | "high_count" | "medium_count" | "low_count" | "avg_review_time_hours" | "approval_rate" | "agreement_rate">;
    
    
    BorderProximity: EnumViewer<'BorderProximity', "ADJACENT" | "NEAR" | "MODERATE" | "FAR" | "DISTANT">;
    
    CapacityLevel: EnumViewer<'CapacityLevel', "GRASSROOTS" | "EMERGING" | "ESTABLISHED" | "MATURE" | "MAJOR_INSTITUTION">;
    
    ExpertDecision: EnumViewer<'ExpertDecision', "PASS" | "FAIL" | "UNCERTAIN">;
    
    FilingRecencyLevel: EnumViewer<'FilingRecencyLevel', "CURRENT" | "RECENT" | "MODERATE" | "OLD" | "VERY_OLD" | "STALE">;
    
    FundingStability: EnumViewer<'FundingStability', "STABLE" | "GROWING" | "DECLINING" | "NEW" | "SPORADIC">;
    
    GrantHistoryStatus: EnumViewer<'GrantHistoryStatus', "ESTABLISHED" | "PROVEN" | "EMERGING" | "MINIMAL" | "UNKNOWN">;
    
    GrantSizeBand: EnumViewer<'GrantSizeBand', "MICRO" | "SMALL" | "MEDIUM" | "LARGE" | "MAJOR" | "TRANSFORMATIONAL">;
    
    GrantSizeFit: EnumViewer<'GrantSizeFit', "OPTIMAL" | "GOOD" | "ACCEPTABLE" | "STRETCH" | "UNREALISTIC_TOO_LARGE" | "UNREALISTIC_TOO_SMALL">;
    
    NTEEDataSource: EnumViewer<'NTEEDataSource', "BMF" | "SCHEDULE_I" | "WEBSITE" | "USER_PROVIDED" | "UNKNOWN">;
    
    NTEEMatchLevel: EnumViewer<'NTEEMatchLevel', "EXACT_FULL" | "EXACT_MAJOR" | "RELATED_MAJOR" | "NO_MATCH">;
    
    RecommendationType: EnumViewer<'RecommendationType', "PEER_FUNDER" | "CLUSTER_MEMBER" | "BRIDGE_FUNDER" | "EMERGING_FUNDER" | "GEOGRAPHIC_MATCH">;
    
    TriagePriority: EnumViewer<'TriagePriority', "CRITICAL" | "HIGH" | "MEDIUM" | "LOW">;
    
    TriageStatus: EnumViewer<'TriageStatus', "PENDING" | "IN_REVIEW" | "APPROVED" | "REJECTED" | "ESCALATED" | "DEFERRED">;
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "BorderProximityAnalysis","BundledGrantee","CoFundingAnalysisInput","CoFundingAnalysisOutput","CompositeScoreResult","FilingRecencyAnalysis","FoundationOpportunityData","FoundationOverlap","FunderRecommendation","FunderSimilarity","FundingSource","GrantHistoryAnalysis","GrantSizeAnalysis","GranteeBundlingInput","GranteeBundlingOutput","NTEECode","NTEEScoreResult","NTEEVoteResult","PeerFunderGroup","RecipientVote","ReliabilitySafeguardsResult","ScheduleIAnalysis","ThematicCluster","TriageItem","TriageQueueStats",
          ]),
          enums: new Set([
            "BorderProximity","CapacityLevel","ExpertDecision","FilingRecencyLevel","FundingStability","GrantHistoryStatus","GrantSizeBand","GrantSizeFit","NTEEDataSource","NTEEMatchLevel","RecommendationType","TriagePriority","TriageStatus",
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.BorderProximityAnalysis = this.tb.classViewer("BorderProximityAnalysis", [
          "distance_to_border_miles","nearest_border_state","proximity_level","proximity_score","boost","explanation","cross_border_eligible",
        ]);
        
        this.BundledGrantee = this.tb.classViewer("BundledGrantee", [
          "grantee_ein","grantee_name","normalized_name","funder_count","total_funding","average_grant_size","funding_sources","first_grant_year","last_grant_year","funding_consistency","geographic_location","common_purposes","purpose_diversity_score","funding_stability","co_funding_strength",
        ]);
        
        this.CoFundingAnalysisInput = this.tb.classViewer("CoFundingAnalysisInput", [
          "bundling_results","similarity_threshold","max_peer_funders","include_network_graph",
        ]);
        
        this.CoFundingAnalysisOutput = this.tb.classViewer("CoFundingAnalysisOutput", [
          "funder_similarity_pairs","highly_similar_pairs","peer_funder_groups","foundation_network_graph","network_statistics","recommendations","processing_time_seconds","analysis_date",
        ]);
        
        this.CompositeScoreResult = this.tb.classViewer("CompositeScoreResult", [
          "final_score","recommendation","ntee_alignment_score","geographic_match_score","recipient_coherence_score","financial_capacity_score","grant_size_fit_score","application_policy_score","filing_recency_score","foundation_type_score","coherence_boost","time_decay_penalty","ntee_explanation","confidence","should_abstain","schedule_i_analysis","grant_size_analysis","abstain_reason",
        ]);
        
        this.FilingRecencyAnalysis = this.tb.classViewer("FilingRecencyAnalysis", [
          "tax_year","years_ago","recency_level","recency_score","penalty","explanation","warning",
        ]);
        
        this.FoundationOpportunityData = this.tb.classViewer("FoundationOpportunityData", [
          "foundation_ein","foundation_name","ntee_codes","ntee_code_sources","ntee_code_dates","schedule_i_grantees","typical_grant_amount","grant_amount_min","grant_amount_max","geographic_focus_states","total_assets","grants_paid_total","accepts_applications","most_recent_filing_year",
        ]);
        
        this.FoundationOverlap = this.tb.classViewer("FoundationOverlap", [
          "foundation_ein_1","foundation_name_1","foundation_ein_2","foundation_name_2","shared_grantees_count","shared_grantee_eins","total_overlap_funding","jaccard_similarity","overlap_percentage_1","overlap_percentage_2",
        ]);
        
        this.FunderRecommendation = this.tb.classViewer("FunderRecommendation", [
          "recommended_foundation_ein","recommended_foundation_name","recommendation_type","rationale","confidence_score","supporting_evidence","shared_funders","similarity_to_current_funders","estimated_grant_range","suggested_approach","priority",
        ]);
        
        this.FunderSimilarity = this.tb.classViewer("FunderSimilarity", [
          "foundation_ein_1","foundation_name_1","foundation_ein_2","foundation_name_2","similarity_score","jaccard_similarity","shared_grantees_count","total_co_funding_amount","average_co_grant_size","recency_score","funding_years_overlap","shared_grantees","common_geographic_focus","common_thematic_focus",
        ]);
        
        this.FundingSource = this.tb.classViewer("FundingSource", [
          "foundation_ein","foundation_name","grant_amount","grant_year","grant_purpose","grant_tier",
        ]);
        
        this.GrantHistoryAnalysis = this.tb.classViewer("GrantHistoryAnalysis", [
          "years_of_grants","total_grants","avg_grants_per_year","history_status","history_score","penalty","is_mirage","explanation","recommendation",
        ]);
        
        this.GrantSizeAnalysis = this.tb.classViewer("GrantSizeAnalysis", [
          "grant_amount","org_revenue","grant_size_band","capacity_level","grant_to_revenue_ratio","fit_level","fit_score","multiplier","explanation","recommendations",
        ]);
        
        this.GranteeBundlingInput = this.tb.classViewer("GranteeBundlingInput", [
          "foundation_eins","tax_years","min_foundations","include_grant_purposes","geographic_filter","min_grant_amount","normalize_recipient_names","fuzzy_matching_threshold",
        ]);
        
        this.GranteeBundlingOutput = this.tb.classViewer("GranteeBundlingOutput", [
          "total_foundations_analyzed","foundation_eins","tax_years_analyzed","total_unique_grantees","bundled_grantees","single_funder_grantees_count","foundation_overlap_matrix","top_co_funded_orgs","thematic_clusters","total_grants_analyzed","total_funding_amount","average_grants_per_foundation","average_grantees_per_foundation","data_completeness_score","recipient_matching_confidence","processing_time_seconds","analysis_date","api_cost_usd",
        ]);
        
        this.NTEECode = this.tb.classViewer("NTEECode", [
          "full_code","major","leaf","source","source_date","confidence",
        ]);
        
        this.NTEEScoreResult = this.tb.classViewer("NTEEScoreResult", [
          "score","match_level","profile_codes","foundation_codes","major_score","leaf_score","time_decay_factor","confidence","explanation","weighted_score",
        ]);
        
        this.NTEEVoteResult = this.tb.classViewer("NTEEVoteResult", [
          "ntee_code","total_votes","vote_count","total_grant_amount","avg_grant_amount","recipients",
        ]);
        
        this.PeerFunderGroup = this.tb.classViewer("PeerFunderGroup", [
          "cluster_id","cluster_name","member_foundations","member_count","shared_focus_areas","geographic_concentration","average_grant_size","total_cluster_funding","cluster_density","bridge_foundations",
        ]);
        
        this.RecipientVote = this.tb.classViewer("RecipientVote", [
          "recipient_name","recipient_ein","grant_amount","grant_year","ntee_codes","ein_confidence","vote_weight",
        ]);
        
        this.ReliabilitySafeguardsResult = this.tb.classViewer("ReliabilitySafeguardsResult", [
          "filing_recency","grant_history","border_proximity","reliability_score","total_penalty","total_boost","net_adjustment","has_reliability_concerns","concerns","overall_assessment","recommendation",
        ]);
        
        this.ScheduleIAnalysis = this.tb.classViewer("ScheduleIAnalysis", [
          "foundation_ein","total_recipients","total_grant_amount","analysis_years","ntee_votes","top_ntee_codes","coherence_score","entropy_score","concentration_ratio","ein_resolution_rate","high_confidence_rate","is_coherent","recommended_boost",
        ]);
        
        this.ThematicCluster = this.tb.classViewer("ThematicCluster", [
          "cluster_id","cluster_name","grantee_count","total_funding","member_grantees","common_keywords","funding_foundations",
        ]);
        
        this.TriageItem = this.tb.classViewer("TriageItem", [
          "item_id","profile_ein","profile_name","foundation_ein","foundation_name","composite_score","confidence","abstain_reason","ntee_score","geographic_score","coherence_score","grant_size_score","status","priority","created_at","assigned_to","expert_decision","expert_rationale","reviewed_at","reviewed_by","notes","tags",
        ]);
        
        this.TriageQueueStats = this.tb.classViewer("TriageQueueStats", [
          "total_items","pending_count","in_review_count","approved_count","rejected_count","critical_count","high_count","medium_count","low_count","avg_review_time_hours","approval_rate","agreement_rate",
        ]);
        
        
        this.BorderProximity = this.tb.enumViewer("BorderProximity", [
          "ADJACENT","NEAR","MODERATE","FAR","DISTANT",
        ]);
        
        this.CapacityLevel = this.tb.enumViewer("CapacityLevel", [
          "GRASSROOTS","EMERGING","ESTABLISHED","MATURE","MAJOR_INSTITUTION",
        ]);
        
        this.ExpertDecision = this.tb.enumViewer("ExpertDecision", [
          "PASS","FAIL","UNCERTAIN",
        ]);
        
        this.FilingRecencyLevel = this.tb.enumViewer("FilingRecencyLevel", [
          "CURRENT","RECENT","MODERATE","OLD","VERY_OLD","STALE",
        ]);
        
        this.FundingStability = this.tb.enumViewer("FundingStability", [
          "STABLE","GROWING","DECLINING","NEW","SPORADIC",
        ]);
        
        this.GrantHistoryStatus = this.tb.enumViewer("GrantHistoryStatus", [
          "ESTABLISHED","PROVEN","EMERGING","MINIMAL","UNKNOWN",
        ]);
        
        this.GrantSizeBand = this.tb.enumViewer("GrantSizeBand", [
          "MICRO","SMALL","MEDIUM","LARGE","MAJOR","TRANSFORMATIONAL",
        ]);
        
        this.GrantSizeFit = this.tb.enumViewer("GrantSizeFit", [
          "OPTIMAL","GOOD","ACCEPTABLE","STRETCH","UNREALISTIC_TOO_LARGE","UNREALISTIC_TOO_SMALL",
        ]);
        
        this.NTEEDataSource = this.tb.enumViewer("NTEEDataSource", [
          "BMF","SCHEDULE_I","WEBSITE","USER_PROVIDED","UNKNOWN",
        ]);
        
        this.NTEEMatchLevel = this.tb.enumViewer("NTEEMatchLevel", [
          "EXACT_FULL","EXACT_MAJOR","RELATED_MAJOR","NO_MATCH",
        ]);
        
        this.RecommendationType = this.tb.enumViewer("RecommendationType", [
          "PEER_FUNDER","CLUSTER_MEMBER","BRIDGE_FUNDER","EMERGING_FUNDER","GEOGRAPHIC_MATCH",
        ]);
        
        this.TriagePriority = this.tb.enumViewer("TriagePriority", [
          "CRITICAL","HIGH","MEDIUM","LOW",
        ]);
        
        this.TriageStatus = this.tb.enumViewer("TriageStatus", [
          "PENDING","IN_REVIEW","APPROVED","REJECTED","ESCALATED","DEFERRED",
        ]);
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}