/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum BorderProximity {
  ADJACENT = "ADJACENT",
  NEAR = "NEAR",
  MODERATE = "MODERATE",
  FAR = "FAR",
  DISTANT = "DISTANT",
}

export enum CapacityLevel {
  GRASSROOTS = "GRASSROOTS",
  EMERGING = "EMERGING",
  ESTABLISHED = "ESTABLISHED",
  MATURE = "MATURE",
  MAJOR_INSTITUTION = "MAJOR_INSTITUTION",
}

export enum ExpertDecision {
  PASS = "PASS",
  FAIL = "FAIL",
  UNCERTAIN = "UNCERTAIN",
}

export enum FilingRecencyLevel {
  CURRENT = "CURRENT",
  RECENT = "RECENT",
  MODERATE = "MODERATE",
  OLD = "OLD",
  VERY_OLD = "VERY_OLD",
  STALE = "STALE",
}

export enum FundingStability {
  STABLE = "STABLE",
  GROWING = "GROWING",
  DECLINING = "DECLINING",
  NEW = "NEW",
  SPORADIC = "SPORADIC",
}

export enum GrantHistoryStatus {
  ESTABLISHED = "ESTABLISHED",
  PROVEN = "PROVEN",
  EMERGING = "EMERGING",
  MINIMAL = "MINIMAL",
  UNKNOWN = "UNKNOWN",
}

export enum GrantSizeBand {
  MICRO = "MICRO",
  SMALL = "SMALL",
  MEDIUM = "MEDIUM",
  LARGE = "LARGE",
  MAJOR = "MAJOR",
  TRANSFORMATIONAL = "TRANSFORMATIONAL",
}

export enum GrantSizeFit {
  OPTIMAL = "OPTIMAL",
  GOOD = "GOOD",
  ACCEPTABLE = "ACCEPTABLE",
  STRETCH = "STRETCH",
  UNREALISTIC_TOO_LARGE = "UNREALISTIC_TOO_LARGE",
  UNREALISTIC_TOO_SMALL = "UNREALISTIC_TOO_SMALL",
}

export enum NTEEDataSource {
  BMF = "BMF",
  SCHEDULE_I = "SCHEDULE_I",
  WEBSITE = "WEBSITE",
  USER_PROVIDED = "USER_PROVIDED",
  UNKNOWN = "UNKNOWN",
}

export enum NTEEMatchLevel {
  EXACT_FULL = "EXACT_FULL",
  EXACT_MAJOR = "EXACT_MAJOR",
  RELATED_MAJOR = "RELATED_MAJOR",
  NO_MATCH = "NO_MATCH",
}

export enum RecommendationType {
  PEER_FUNDER = "PEER_FUNDER",
  CLUSTER_MEMBER = "CLUSTER_MEMBER",
  BRIDGE_FUNDER = "BRIDGE_FUNDER",
  EMERGING_FUNDER = "EMERGING_FUNDER",
  GEOGRAPHIC_MATCH = "GEOGRAPHIC_MATCH",
}

export enum TriagePriority {
  CRITICAL = "CRITICAL",
  HIGH = "HIGH",
  MEDIUM = "MEDIUM",
  LOW = "LOW",
}

export enum TriageStatus {
  PENDING = "PENDING",
  IN_REVIEW = "IN_REVIEW",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  ESCALATED = "ESCALATED",
  DEFERRED = "DEFERRED",
}

export interface BorderProximityAnalysis {
  distance_to_border_miles: number
  nearest_border_state?: string | null
  proximity_level: BorderProximity
  proximity_score: number
  boost: number
  explanation: string
  cross_border_eligible: boolean
  
}

export interface BundledGrantee {
  grantee_ein?: string | null
  grantee_name: string
  normalized_name: string
  funder_count: number
  total_funding: number
  average_grant_size: number
  funding_sources: FundingSource[]
  first_grant_year: number
  last_grant_year: number
  funding_consistency: number
  geographic_location?: string | null
  common_purposes: string[]
  purpose_diversity_score: number
  funding_stability: FundingStability
  co_funding_strength: number
  
}

export interface CoFundingAnalysisInput {
  bundling_results: string
  similarity_threshold: number
  max_peer_funders: number
  include_network_graph: boolean
  
}

export interface CoFundingAnalysisOutput {
  funder_similarity_pairs: FunderSimilarity[]
  highly_similar_pairs: FunderSimilarity[]
  peer_funder_groups: PeerFunderGroup[]
  foundation_network_graph?: Record<string, string> | null
  network_statistics: Record<string, string>
  recommendations: FunderRecommendation[]
  processing_time_seconds: number
  analysis_date: string
  
}

export interface CompositeScoreResult {
  final_score: number
  recommendation: string
  ntee_alignment_score: number
  geographic_match_score: number
  recipient_coherence_score: number
  financial_capacity_score: number
  grant_size_fit_score: number
  application_policy_score: number
  filing_recency_score: number
  foundation_type_score: number
  coherence_boost: number
  time_decay_penalty: number
  ntee_explanation: string
  confidence: number
  should_abstain: boolean
  schedule_i_analysis?: Record<string, string> | null
  grant_size_analysis?: Record<string, string> | null
  abstain_reason?: string | null
  
}

export interface FilingRecencyAnalysis {
  tax_year: number
  years_ago: number
  recency_level: FilingRecencyLevel
  recency_score: number
  penalty: number
  explanation: string
  warning?: string | null
  
}

export interface FoundationOpportunityData {
  foundation_ein: string
  foundation_name: string
  ntee_codes: string[]
  ntee_code_sources: Record<string, string>
  ntee_code_dates?: Record<string, string> | null
  schedule_i_grantees?: string | null
  typical_grant_amount?: number | null
  grant_amount_min?: number | null
  grant_amount_max?: number | null
  geographic_focus_states: string[]
  total_assets?: number | null
  grants_paid_total?: number | null
  accepts_applications?: boolean | null
  most_recent_filing_year?: number | null
  
}

export interface FoundationOverlap {
  foundation_ein_1: string
  foundation_name_1: string
  foundation_ein_2: string
  foundation_name_2: string
  shared_grantees_count: number
  shared_grantee_eins: string[]
  total_overlap_funding: number
  jaccard_similarity: number
  overlap_percentage_1: number
  overlap_percentage_2: number
  
}

export interface FunderRecommendation {
  recommended_foundation_ein: string
  recommended_foundation_name: string
  recommendation_type: RecommendationType
  rationale: string
  confidence_score: number
  supporting_evidence: string[]
  shared_funders: string[]
  similarity_to_current_funders: number
  estimated_grant_range: string
  suggested_approach: string
  priority: string
  
}

export interface FunderSimilarity {
  foundation_ein_1: string
  foundation_name_1: string
  foundation_ein_2: string
  foundation_name_2: string
  similarity_score: number
  jaccard_similarity: number
  shared_grantees_count: number
  total_co_funding_amount: number
  average_co_grant_size: number
  recency_score: number
  funding_years_overlap: number[]
  shared_grantees: string[]
  common_geographic_focus?: string | null
  common_thematic_focus: string[]
  
}

export interface FundingSource {
  foundation_ein: string
  foundation_name: string
  grant_amount: number
  grant_year: number
  grant_purpose?: string | null
  grant_tier?: string | null
  
}

export interface GrantHistoryAnalysis {
  years_of_grants: number
  total_grants: number
  avg_grants_per_year: number
  history_status: GrantHistoryStatus
  history_score: number
  penalty: number
  is_mirage: boolean
  explanation: string
  recommendation: string
  
}

export interface GrantSizeAnalysis {
  grant_amount: number
  org_revenue: number
  grant_size_band: GrantSizeBand
  capacity_level: CapacityLevel
  grant_to_revenue_ratio: number
  fit_level: GrantSizeFit
  fit_score: number
  multiplier: number
  explanation: string
  recommendations: string
  
}

export interface GranteeBundlingInput {
  foundation_eins: string[]
  tax_years: number[]
  min_foundations: number
  include_grant_purposes: boolean
  geographic_filter?: string[] | null
  min_grant_amount: number
  normalize_recipient_names: boolean
  fuzzy_matching_threshold: number
  
}

export interface GranteeBundlingOutput {
  total_foundations_analyzed: number
  foundation_eins: string[]
  tax_years_analyzed: number[]
  total_unique_grantees: number
  bundled_grantees: BundledGrantee[]
  single_funder_grantees_count: number
  foundation_overlap_matrix: FoundationOverlap[]
  top_co_funded_orgs: BundledGrantee[]
  thematic_clusters: ThematicCluster[]
  total_grants_analyzed: number
  total_funding_amount: number
  average_grants_per_foundation: number
  average_grantees_per_foundation: number
  data_completeness_score: number
  recipient_matching_confidence: number
  processing_time_seconds: number
  analysis_date: string
  api_cost_usd: number
  
}

export interface NTEECode {
  full_code: string
  major: string
  leaf?: string | null
  source: NTEEDataSource
  source_date?: string | null
  confidence: number
  
}

export interface NTEEScoreResult {
  score: number
  match_level: NTEEMatchLevel
  profile_codes: NTEECode[]
  foundation_codes: NTEECode[]
  major_score: number
  leaf_score: number
  time_decay_factor: number
  confidence: number
  explanation: string
  weighted_score: number
  
}

export interface NTEEVoteResult {
  ntee_code: string
  total_votes: number
  vote_count: number
  total_grant_amount: number
  avg_grant_amount: number
  recipients: string[]
  
}

export interface PeerFunderGroup {
  cluster_id: string
  cluster_name: string
  member_foundations: string[]
  member_count: number
  shared_focus_areas: string[]
  geographic_concentration?: string | null
  average_grant_size: number
  total_cluster_funding: number
  cluster_density: number
  bridge_foundations: string[]
  
}

export interface RecipientVote {
  recipient_name: string
  recipient_ein?: string | null
  grant_amount: number
  grant_year: number
  ntee_codes: string[]
  ein_confidence: string
  vote_weight: number
  
}

export interface ReliabilitySafeguardsResult {
  filing_recency: FilingRecencyAnalysis
  grant_history: GrantHistoryAnalysis
  border_proximity: BorderProximityAnalysis
  reliability_score: number
  total_penalty: number
  total_boost: number
  net_adjustment: number
  has_reliability_concerns: boolean
  concerns: string[]
  overall_assessment: string
  recommendation: string
  
}

export interface ScheduleIAnalysis {
  foundation_ein: string
  total_recipients: number
  total_grant_amount: number
  analysis_years: number[]
  ntee_votes: Record<string, NTEEVoteResult>
  top_ntee_codes: string[]
  coherence_score: number
  entropy_score: number
  concentration_ratio: number
  ein_resolution_rate: number
  high_confidence_rate: number
  is_coherent: boolean
  recommended_boost: number
  
}

export interface ThematicCluster {
  cluster_id: string
  cluster_name: string
  grantee_count: number
  total_funding: number
  member_grantees: string[]
  common_keywords: string[]
  funding_foundations: string[]
  
}

export interface TriageItem {
  item_id: string
  profile_ein: string
  profile_name: string
  foundation_ein: string
  foundation_name: string
  composite_score: number
  confidence: number
  abstain_reason: string
  ntee_score: number
  geographic_score: number
  coherence_score: number
  grant_size_score: number
  status: TriageStatus
  priority: TriagePriority
  created_at: string
  assigned_to?: string | null
  expert_decision?: ExpertDecision | null
  expert_rationale?: string | null
  reviewed_at?: string | null
  reviewed_by?: string | null
  notes: string[]
  tags: string[]
  
}

export interface TriageQueueStats {
  total_items: number
  pending_count: number
  in_review_count: number
  approved_count: number
  rejected_count: number
  critical_count: number
  high_count: number
  medium_count: number
  low_count: number
  avg_review_time_hours: number
  approval_rate: number
  agreement_rate: number
  
}
